"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        // Navigation
        "nav.home": "Home",
        "nav.cars": "Our Fleet",
        "nav.about": "About Us",
        "nav.contact": "Contact",
        "nav.bookNow": "Book Now",
        "nav.companyName": "Al-Taj",
        "nav.tagline": "Car Rental",

        // Hero
        "hero.alTaj": "Al-Taj",
        "hero.carRental": "Car Rental",
        "hero.title": "Experience Luxury",
        "hero.titleHighlight": "On Every Journey",
        "hero.tagline": "Experience luxury and elegance with our premium fleet. Your journey deserves the finest vehicles.",
        "hero.subtitle": "Discover our premium collection of luxury vehicles for an unforgettable driving experience",
        "hero.browseFleet": "Browse Our Fleet",
        "hero.learnMore": "Learn More",
        "hero.contactUs": "Contact Us",

        // Stats
        "stats.premiumCars": "Premium Cars",
        "stats.happyCustomers": "Happy Customers",
        "stats.yearsExperience": "Years Experience",
        "stats.citiesCovered": "Cities Covered",

        // Cars
        "cars.heroTitle": "Our Premium Fleet",
        "cars.heroSubtitle": "Discover our collection of luxury vehicles. Each car is meticulously maintained to ensure your comfort and safety.",
        "cars.title": "Our Fleet",
        "cars.subtitle": "Explore our premium collection",
        "cars.search": "Search by name or model...",
        "cars.priceRange": "Price Range",
        "cars.status": "Status",
        "cars.all": "All",
        "cars.available": "Available",
        "cars.rented": "Rented",
        "cars.maintenance": "Maintenance",
        "cars.perDay": "/day",
        "cars.viewDetails": "View Details",
        "cars.bookNow": "Book Now",
        "cars.noResults": "No cars found matching your criteria",
        "cars.emptyMessage": "No cars match your search criteria. Try adjusting your filters.",
        "cars.features": "Features",
        "cars.specifications": "Specifications",
        "cars.model": "Model",
        "cars.year": "Year",
        "cars.color": "Color",
        "cars.dailyRate": "Daily Rate",
        "cars.showingCount": "Showing {count} of {total} cars",
        "cars.tryAgain": "Try Again",

        // Booking
        "booking.title": "Complete Your",
        "booking.titleHighlight": "Booking",
        "booking.personalInfo": "Personal Information",
        "booking.fullName": "Full Name",
        "booking.fullNamePlaceholder": "Enter your full name",
        "booking.phone": "Phone Number",
        "booking.phonePlaceholder": "+964 7XX XXX XXXX",
        "booking.email": "Email (Optional)",
        "booking.emailPlaceholder": "your@email.com",
        "booking.branch": "Pickup Branch",
        "booking.selectBranch": "Select Branch",
        "booking.selectBranchPlaceholder": "Select Branch",
        "booking.rentalPeriod": "Rental Period",
        "booking.pickupDate": "Pick-up Date",
        "booking.returnDate": "Return Date",
        "booking.pickupTime": "Pickup Time",
        "booking.notes": "Additional Notes",
        "booking.notesPlaceholder": "Any special requests or comments...",
        "booking.confirm": "Confirm Booking",
        "booking.processing": "Processing...",
        "booking.summary": "Booking Summary",
        "booking.duration": "Duration",
        "booking.days": "days",
        "booking.day": "day",
        "booking.total": "Total",
        "booking.dailyPrice": "Daily Price",
        "booking.payOnDelivery": "Pay on Delivery",
        "booking.noPaymentNow": "No upfront payment required",
        "booking.payOnDeliveryTitle": "Pay on Delivery",
        "booking.payOnDeliveryText": "No upfront payment required. Pay when you pick up your car.",
        "booking.success": "Booking Confirmed!",
        "booking.successMessage": "Your booking request has been submitted. We will contact you shortly to confirm.",
        "booking.browseMore": "Browse More Cars",
        "booking.goHome": "Go Home",
        "booking.backToDetails": "Back to Car Details",
        "booking.backToFleet": "Back to Fleet",
        "booking.availableAt": "Available At",
        "booking.callToBook": "Call to Book",
        "booking.pleaseContact": "Please contact us for availability.",
        "booking.step1Title": "Step 1: Choose Date & Time",
        "booking.step2Title": "Step 2: Choose Your Car",
        "booking.step3Title": "Step 3: Complete Details",
        "booking.step1Label": "Date & Time",
        "booking.step2Label": "Choose Car",
        "booking.step3Label": "Personal Info",
        "booking.searchCars": "Search Available Cars",
        "booking.availableCarsCount": "Available Cars",
        "booking.noAvailableCars": "No cars available for these dates in this branch",
        "booking.tryDifferentDates": "Try choosing different dates or another branch",
        "booking.carsAvailableBadge": "cars available",
        "booking.totalAmount": "Total Amount",
        "booking.chooseCar": "Book Your Car",
        "booking.continue": "Continue",
        "booking.changeDates": "Change Dates",
        "booking.changeCar": "Change Car",
        "booking.selectDatePrompt": "Choose the date and we'll show you available cars",

        // About
        "about.title": "About",
        "about.titleHighlight": "Al-Taj",
        "about.heroSubtitle": "Your trusted partner for premium car rental services in Iraq. We pride ourselves on delivering excellence, luxury, and unparalleled customer service.",
        "about.story": "Our Story",
        "about.storyText": "Al-Taj Car Rental was founded with a vision to provide exceptional luxury car rental services. We believe every journey should be memorable.",
        "about.storyPart1": "Al-Taj Car Rental was founded with a vision to revolutionize the car rental experience. We understand that every journey is special, whether it's a business trip, family vacation, or a luxurious getaway.",
        "about.storyPart2": "With over 10 years of experience, we have built a reputation for providing top-tier vehicles, exceptional customer service, and competitive pricing. Our fleet includes the latest models from world-renowned manufacturers, ensuring comfort, safety, and style.",
        "about.mission": "Our Mission",
        "about.missionText": "To deliver premium vehicle rentals with outstanding customer service, making luxury accessible to everyone.",
        "about.missionDescription": "To provide the finest car rental experience through exceptional service, premium vehicles, and unwavering commitment to customer satisfaction. We aim to make every journey memorable and every mile luxurious.",
        "about.whyChoose": "Why Choose Al-Taj?",
        "about.premiumFleet": "Premium Fleet",
        "about.premiumFleetDesc": "Luxury vehicles from top brands, meticulously maintained for your comfort",
        "about.service247": "24/7 Service",
        "about.service247Desc": "Round-the-clock support for all your needs",
        "about.bestPrices": "Best Prices",
        "about.bestPricesDesc": "Competitive rates with transparent pricing and no hidden fees",
        "about.easyBooking": "Easy Booking",
        "about.easyBookingDesc": "Simple and fast reservation process",
        "about.insured": "Fully Insured",
        "about.insuredDesc": "Comprehensive insurance coverage for complete peace of mind",
        "about.excellence": "Excellence",
        "about.excellenceDesc": "We strive for perfection in everything we do, from vehicle maintenance to customer interactions.",
        "about.trust": "Trust",
        "about.trustDesc": "Building lasting relationships through transparency, reliability, and honest business practices.",
        "about.innovation": "Innovation",
        "about.innovationDesc": "Continuously improving our services and adopting new technologies for your convenience.",

        // Added New Sections
        "about.servicesTitle": "What We Offer",
        "about.service1Title": "Transportation & Delivery",
        "about.service1Desc": "Freight shipping inside and outside Iraq, plus private drivers for delegations, individuals, and tours between provinces.",
        "about.service2Title": "Vehicle Tracking",
        "about.service2Desc": "Monitor location, movement, and speed with emergency remote shutdown features for maximum security.",
        "about.service3Title": "First Licensed Rental",
        "about.service3Desc": "The first government-registered company in Iraq for daily, weekly, or monthly rentals. Fully insured and driver-free.",

        "about.faqTitle": "Frequently Asked Questions",
        "about.faq1Q": "What if the car breaks down while driving?",
        "about.faq1A1": "Please notify us immediately. We will provide a replacement while we repair the car.",
        "about.faq1A2": "Do not attempt repairs yourself or take the car to an unauthorized workshop.",
        "about.faq2Q": "What are my rights as a renter?",
        "about.faq2A1": "You can drive across all of Iraq except Kurdistan. Daily limit is 200km (500 IQD/km extra).",
        "about.faq2A2": "All cars have comprehensive insurance. You only pay 150,000 IQD for the traffic report in case of an accident.",
        "about.faq3Q": "What are the rental requirements?",
        "about.faq3A1": "Refundable deposit of 750,000 IQD and your original passport.",
        "about.faq3A2": "Original residency card and a valid Iraqi or foreign driver's license.",

        // Contact
        "contact.title": "Get in",
        "contact.titleHighlight": "Touch",
        "contact.subtitle": "Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
        "contact.phone": "Phone",
        "contact.email": "Email",
        "contact.address": "Location",
        "contact.monFri": "Available 24/7",
        "contact.formTitle": "Send us a Message",
        "contact.fullName": "Full Name",
        "contact.emailAddr": "Email Address",
        "contact.phoneNum": "Phone Number",
        "contact.messageLabel": "Message",
        "contact.placeholderName": "Enter your full name",
        "contact.placeholderEmail": "your@email.com",
        "contact.placeholderPhone": "+964XXXXXXXXX",
        "contact.placeholderMessage": "Tell us how we can help you...",
        "contact.sendMessage": "Send Message",
        "contact.send": "Send",
        "contact.sending": "Sending...",
        "contact.successMessage": "Message sent successfully! We will get back to you soon.",

        // Footer
        "footer.quickLinks": "Quick Links",
        "footer.contactUs": "Contact Us",
        "footer.followUs": "Follow Us",
        "footer.rights": "© {year} Al-Taj Car Rental. All rights reserved.",
        "footer.privacy": "Privacy Policy",
        "footer.terms": "Terms of Service",

        // Admin
        "admin.dashboard": "Dashboard",
        "admin.cars": "Cars",
        "admin.bookings": "Bookings",
        "admin.calendar": "Calendar",
        "admin.crm": "Customers",
        "admin.categories": "Categories",
        "admin.branches": "Branches",
        "admin.exitAdmin": "Exit Admin",
        "admin.viewSite": "View Site",
        "admin.welcome": "Welcome to",
        "admin.welcomeHighlight": "Al-Taj Admin",
        "admin.manageFleet": "Manage your fleet, bookings, and categories from here.",
        "admin.totalCars": "Total Cars",
        "admin.availableCars": "Available",
        "admin.totalBookings": "Total Bookings",
        "admin.pending": "Pending",
        "admin.totalRevenue": "Total Revenue",
        "admin.revenueNote": "From confirmed and completed bookings",
        "admin.recentBookings": "Recent Bookings",
        "admin.viewAll": "View All",
        "admin.noBookingsYet": "No bookings yet. They will appear here once customers start booking.",
        "admin.addNewCar": "Add New Car",
        "admin.manageBookings": "Manage Bookings",
        "admin.addVehicle": "Add a vehicle to your fleet",
        "admin.viewReservations": "View and update reservations",
        "admin.organizeTypes": "Organize your vehicle types",
        "admin.newBookings": "new",

        // Admin Bookings
        "admin.manageBookingsTitle": "Manage Bookings",
        "admin.totalBookingsCount": "total bookings",
        "admin.searchBookings": "Search by customer name, phone, car or branch...",
        "admin.allStatus": "All Status",
        "admin.statusPending": "Pending",
        "admin.statusConfirmed": "Confirmed",
        "admin.statusCompleted": "Completed",
        "admin.statusCancelled": "Cancelled",
        "admin.noBookingsMatch": "No bookings match your filters",
        "admin.bookingDetails": "Booking Details",
        "admin.customerInfo": "Customer Information",
        "admin.carInfo": "Car",
        "admin.bookingDetailsTitle": "Booking Details",
        "admin.pickupDate": "Pickup Date",
        "admin.returnDate": "Return Date",
        "admin.pickupTime": "Pickup Time",
        "admin.branchLocation": "Branch",
        "admin.totalAmount": "Total Amount",
        "admin.updateStatus": "Update Status",
        "admin.notes": "Notes",

        // Admin Cars
        "admin.manageCars": "Manage Cars",
        "admin.searchCars": "Search by name or model...",
        "admin.noCarsYet": "No cars yet. Add your first car!",
        "admin.noCarsMatch": "No cars match your search",
        "admin.addCar": "Add Car",
        "admin.editCar": "Edit Car",
        "admin.carName": "Car Name",
        "admin.carNameEn": "Name (English)",
        "admin.carNameAr": "Name (Arabic)",
        "admin.carModel": "Model",
        "admin.carYear": "Year",
        "admin.carColor": "Color",
        "admin.carDailyRate": "Daily Rate",
        "admin.carCategory": "Category",
        "admin.carStatus": "Status",
        "admin.carFeatures": "Features",
        "admin.carImages": "Images",
        "admin.uploadImages": "Upload Images",
        "admin.selectCategory": "Select Category",
        "admin.featuresPlaceholder": "e.g. Leather seats, Sunroof, GPS",
        "admin.confirmDelete": "Are you sure you want to delete this?",

        // Admin Categories
        "admin.manageCategories": "Manage Categories",
        "admin.noCategoriesYet": "No categories yet. Add your first category!",
        "admin.addCategory": "Add Category",
        "admin.editCategory": "Edit Category",
        "admin.categoryName": "Category Name",
        "admin.categoryNameEn": "Name (English)",
        "admin.categoryNameAr": "Name (Arabic)",
        "admin.categoryDescription": "Description",

        // Admin Branches
        "admin.manageBranches": "Manage Branches",
        "admin.branchesSubtitle": "Manage pickup and delivery locations",
        "admin.noBranchesYet": "No branches yet. Add your first branch!",
        "admin.addBranch": "Add Branch",
        "admin.editBranch": "Edit Branch",
        "admin.newBranch": "New Branch",
        "admin.branchName": "Branch Name",
        "admin.branchNameEn": "Name (English)",
        "admin.branchNameAr": "Name (Arabic)",
        "admin.branchAddress": "Address",
        "admin.branchAddressEn": "Address (English)",
        "admin.branchAddressAr": "Address (Arabic)",
        "admin.branchPhone": "Phone",
        "admin.branchActive": "Active",

        // Common
        "common.loading": "Loading...",
        "common.error": "Error",
        "common.save": "Save",
        "common.cancel": "Cancel",
        "common.edit": "Edit",
        "common.delete": "Delete",
        "common.add": "Add",
        "common.update": "Update",
        "common.search": "Search",
        "common.filter": "Filter",
        "common.actions": "Actions",
        "common.status": "Status",
        "common.active": "Active",
        "common.inactive": "Inactive",
        "common.customer": "Customer",
        "common.car": "Car",
        "common.dates": "Dates",
        "common.amount": "Amount",
        "common.name": "Name",
        "common.phone": "Phone",
        "common.email": "Email",
        "common.address": "Address",
        "common.yes": "Yes",
        "common.no": "No",
        "common.confirm": "Confirm",
        "common.close": "Close",
        "common.back": "Back",
        "common.next": "Next",
        "common.required": "Required",
        "common.chatWithUs": "Chat with us",
        "common.whatsappMessage": "Hello, I am interested in renting a car from Al-Taj.",
        "common.optional": "Optional",

        // User Management
        "admin.userManagement": "User Management",
        "admin.users": "Users",
        "admin.addUser": "Add User",
        "admin.editUser": "Edit User",
        "admin.role": "Role",
        "admin.roleSuperAdmin": "Super Admin",
        "admin.roleBranchManager": "Branch Manager",
        "admin.roleStaff": "Staff",
        "admin.assignedBranches": "Assigned Branches",
        "admin.allBranches": "All Branches",
        "admin.activeStatus": "Active Status",
        "admin.fullName": "Full Name",
        "admin.email": "Email",
        "admin.password": "Password",
        "admin.passwordNote": "Leave blank to keep current password when editing",
    },
    ar: {
        // Navigation
        "nav.home": "الرئيسية",
        "nav.cars": "أسطولنا",
        "nav.about": "من نحن",
        "nav.contact": "اتصل بنا",
        "nav.bookNow": "احجز الآن",
        "nav.companyName": "شركة التاج",
        "nav.tagline": "لتأجير السيارات",

        // Hero
        "hero.alTaj": "التاج",
        "hero.carRental": "لتأجير السيارات",
        "hero.title": "عش تجربة الفخامة",
        "hero.titleHighlight": "في كل رحلة",
        "hero.tagline": "استمتع بتجربة الفخامة والأناقة مع أسطولنا المتميز. رحلتك تستحق أرقى السيارات.",
        "hero.subtitle": "اكتشف مجموعتنا المميزة من السيارات الفاخرة لتجربة قيادة لا تُنسى",
        "hero.browseFleet": "تصفح أسطولنا",
        "hero.learnMore": "تعرف علينا",
        "hero.contactUs": "اتصل بنا",

        // Stats
        "stats.premiumCars": "سيارة فاخرة",
        "stats.happyCustomers": "عميل سعيد",
        "stats.yearsExperience": "سنوات خبرة",
        "stats.citiesCovered": "مدن نغطيها",

        // Cars
        "cars.heroTitle": "أسطولنا الفاخر",
        "cars.heroSubtitle": "اكتشف مجموعتنا من السيارات الفاخرة. كل سيارة مصانة بدقة لضمان راحتك وسلامتك.",
        "cars.title": "أسطولنا",
        "cars.subtitle": "استكشف مجموعتنا المميزة",
        "cars.search": "البحث بالاسم أو الموديل...",
        "cars.priceRange": "نطاق السعر",
        "cars.status": "الحالة",
        "cars.all": "الكل",
        "cars.available": "متاح",
        "cars.rented": "مؤجر",
        "cars.maintenance": "صيانة",
        "cars.perDay": "/يوم",
        "cars.viewDetails": "عرض التفاصيل",
        "cars.bookNow": "احجز الآن",
        "cars.noResults": "لا توجد سيارات مطابقة لمعايير البحث",
        "cars.emptyMessage": "لا توجد سيارات تطابق معايير البحث. حاول تعديل الفلاتر.",
        "cars.features": "المميزات",
        "cars.specifications": "المواصفات",
        "cars.model": "الموديل",
        "cars.year": "السنة",
        "cars.color": "اللون",
        "cars.dailyRate": "السعر اليومي",
        "cars.showingCount": "عرض {count} من أصل {total} سيارات",
        "cars.tryAgain": "حاول مرة أخرى",

        // Booking
        "booking.title": "أكمل",
        "booking.titleHighlight": "الحجز",
        "booking.personalInfo": "المعلومات الشخصية",
        "booking.fullName": "الاسم الكامل",
        "booking.fullNamePlaceholder": "أدخل اسمك الكامل",
        "booking.phone": "رقم الهاتف",
        "booking.phonePlaceholder": "+964 7XX XXX XXXX",
        "booking.email": "البريد الإلكتروني (اختياري)",
        "booking.emailPlaceholder": "example@email.com",
        "booking.branch": "فرع الاستلام",
        "booking.selectBranch": "اختر الفرع",
        "booking.selectBranchPlaceholder": "اختر الفرع",
        "booking.rentalPeriod": "فترة الإيجار",
        "booking.pickupDate": "تاريخ الاستلام",
        "booking.returnDate": "تاريخ الإرجاع",
        "booking.pickupTime": "وقت الاستلام",
        "booking.notes": "ملاحظات إضافية",
        "booking.notesPlaceholder": "أي طلبات خاصة أو ملاحظات...",
        "booking.confirm": "تأكيد الحجز",
        "booking.processing": "جاري المعالجة...",
        "booking.summary": "ملخص الحجز",
        "booking.duration": "المدة",
        "booking.days": "أيام",
        "booking.day": "يوم",
        "booking.total": "المجموع",
        "booking.dailyPrice": "السعر اليومي",
        "booking.payOnDelivery": "الدفع عند الاستلام",
        "booking.noPaymentNow": "لا يلزم دفع مقدم الآن",
        "booking.payOnDeliveryTitle": "الدفع عند الاستلام",
        "booking.payOnDeliveryText": "لا يلزم دفع مقدم. ادفع عند استلام السيارة.",
        "booking.success": "تم تأكيد الحجز!",
        "booking.successMessage": "تم استلام طلب الحجز. سنتواصل معك قريباً للتأكيد.",
        "booking.browseMore": "تصفح المزيد",
        "booking.goHome": "الرئيسية",
        "booking.backToDetails": "العودة لتفاصيل السيارة",
        "booking.backToFleet": "العودة للأسطول",
        "booking.availableAt": "متوفر في",
        "booking.callToBook": "اتصل للحجز",
        "booking.pleaseContact": "يرجى الاتصال بنا للتأكد من التوفر.",
        "booking.step1Title": "الخطوة 1: اختر التاريخ والوقت",
        "booking.step2Title": "الخطوة 2: اختر السيارة",
        "booking.step3Title": "الخطوة 3: أكمل بياناتك",
        "booking.step1Label": "التاريخ والوقت",
        "booking.step2Label": "اختر السيارة",
        "booking.step3Label": "المعلومات الشخصية",
        "booking.searchCars": "بحث عن السيارات المتوفرة",
        "booking.availableCarsCount": "السيارات المتوفرة",
        "booking.noAvailableCars": "لا توجد سيارات متوفرة في هذه الفترة في هذا الفرع",
        "booking.tryDifferentDates": "جرب اختيار تواريخ أخرى أو فرع آخر",
        "booking.carsAvailableBadge": "سيارات متوفرة",
        "booking.totalAmount": "المجموع الكلي",
        "booking.chooseCar": "احجز سيارتك",
        "booking.continue": "متابعة",
        "booking.changeDates": "تغيير التاريخ",
        "booking.changeCar": "تغيير السيارة",
        "booking.selectDatePrompt": "اختر التاريخ المناسب وسنعرض لك السيارات المتوفرة",

        // About
        "about.title": "عن",
        "about.titleHighlight": "التاج",
        "about.heroSubtitle": "شريكك الموثوق لخدمات تأجير السيارات الفاخرة في العراق. نفخر بتقديم التميز والفخامة وخدمة عملاء لا مثيل لها.",
        "about.story": "قصتنا",
        "about.storyText": "تأسست شركة التاج لتأجير السيارات برؤية لتقديم خدمات تأجير سيارات فاخرة استثنائية. نؤمن بأن كل رحلة يجب أن تكون لا تُنسى.",
        "about.storyPart1": "تأسست شركة التاج لتأجير السيارات برؤية لإحداث ثورة في تجربة تأجير السيارات. نحن ندرك أن كل رحلة خاصة، سواء كانت رحلة عمل، أو عطلة عائلية، أو ملاذاً فاخراً.",
        "about.storyPart2": "مع أكثر من 10 سنوات من الخبرة، بنينا سمعة طيبة في تقديم سيارات من الدرجة الأولى، وخدمة عملاء استثنائية، وأسعار تنافسية. يضم أسطولنا أحدث الموديلات من الشركات العالمية المصنعة، مما يضمن الراحة والأمان والأناقة.",
        "about.mission": "مهمتنا",
        "about.missionText": "تقديم تأجير سيارات فاخرة مع خدمة عملاء متميزة، مما يجعل الفخامة في متناول الجميع.",
        "about.missionDescription": "تقديم أفضل تجربة تأجير سيارات من خلال خدمة استثنائية، وسيارات فاخرة، والتزام لا يتزعزع برضا العملاء. نهدف إلى جعل كل رحلة لا تُنسى وكل ميل فاخراً.",
        "about.whyChoose": "لماذا تختار التاج؟",
        "about.premiumFleet": "أسطول فاخر",
        "about.premiumFleetDesc": "سيارات فاخرة من أفضل الماركات، مصانة بدقة لضمان راحتك",
        "about.service247": "خدمة 24/7",
        "about.service247Desc": "دعم على مدار الساعة لجميع احتياجاتك",
        "about.bestPrices": "أفضل الأسعار",
        "about.bestPricesDesc": "أسعار تنافسية مع تسعير شفاف وبدون رسوم مخفية",
        "about.easyBooking": "حجز سهل",
        "about.easyBookingDesc": "عملية حجز بسيطة وسريعة",
        "about.insured": "تأمين شامل",
        "about.insuredDesc": "تغطية تأمينية شاملة لراحة بالك التامة",
        "about.excellence": "التميز",
        "about.excellenceDesc": "نحن نسعى جاهدين للكمال في كل ما نقوم به، من صيانة المركبات إلى التعامل مع العملاء.",
        "about.trust": "الثقة",
        "about.trustDesc": "بناء علاقات دائمة من خلال الشفافية والموثوقية والممارسات التجارية الصادقة.",
        "about.innovation": "الابتكار",
        "about.innovationDesc": "تحسين خدماتنا باستمرار واعتماد تقنيات جديدة لراحتك.",

        // Added New Sections
        "about.servicesTitle": "ما نستطيع تقديمه للزبون",
        "about.service1Title": "خدمات النقل والتوصيل",
        "about.service1Desc": "نحن نوفر خدمة شحن البضائع داخل وخارج العراق كما نوفر سائق بسيارة خاصة لنقل الوفود والافراد والجولات السياحية بين المحافظات العراقية.",
        "about.service2Title": "اجهزة تتبع المركبات",
        "about.service2Desc": "اجهزة تتبع تستخدم لمراقبة وتتبع السيارات او الشاحنات، الجهاز مصمم للسماح بمراقبة موقع السيارة وحركتها وسرعتها وكذلك اطفائها في حالات الطوارئ والكثير من الميزات الاخرى.",
        "about.service3Title": "تأجير سيارات",
        "about.service3Desc": "إستاجر سيارتك معنا، نحن اول شركة في العراق رسمية مسجلة ومرخصة من قبل الحكومة العراقية للإيجار اليومي، الإسبوعي او الشهري سيارات مؤمنة بالكامل وبدون سائق.",

        "about.faqTitle": "الاسئلة الشائعة المكررة",
        "about.faq1Q": "ماذا افعل عندما تتعطل السيارة وانا اقود؟",
        "about.faq1A1": "عندما تتعطل السيارة في الطريق يرجى ابلاغنا لنستبدلها ريثما نقوم باصلاحها وارجاعها لك.",
        "about.faq1A2": "لا يجب على المستخدم الذهاب الى اي ورشة اصلاح السيارات او حتى اصلاحها بنفسه.",
        "about.faq2Q": "ما هي حقوق المستاجر؟",
        "about.faq2A1": "للزبون الحق في التجوال في جميع محافظات العراق عدى اقليم كردستان، وله في اليوم ٢٠٠ كيلو متر وفي حال التجاوز يتم احتساب ٥٠٠ دينار عراقي لكل كيلو متر زائد.",
        "about.faq2A2": "جميع السيارات تحتوي على تامين شامل، في حال وقوع حادث سيتوجب عليك دفع مبلغ ١٥٠ الف دينار عراقي لفتح المخطط المروري وسيتكفل التامين بالباقي.",
        "about.faq3Q": "ما هي شروط الايجار؟",
        "about.faq3A1": "تامينات مسترجعة بمبلغ ٧٥٠ الف دينار عراقي + جواز سفر اصلي.",
        "about.faq3A2": "يجب توفر شهادة قيادة عراقية او اجنبية وكذلك بطاقة سكن اصلية.",

        // Contact
        "contact.title": "تواصل",
        "contact.titleHighlight": "معنا",
        "contact.subtitle": "لديك أسئلة؟ يسعدنا سماع صوتك. أرسل لنا رسالة وسنرد عليك في أقرب وقت ممكن.",
        "contact.phone": "الهاتف",
        "contact.email": "البريد الإلكتروني",
        "contact.address": "الموقع",
        "contact.monFri": "متاح 24/7",
        "contact.formTitle": "أرسل لنا رسالة",
        "contact.fullName": "الاسم الكامل",
        "contact.emailAddr": "البريد الإلكتروني",
        "contact.phoneNum": "رقم الهاتف",
        "contact.messageLabel": "الرسالة",
        "contact.placeholderName": "أدخل اسمك الكامل",
        "contact.placeholderEmail": "example@email.com",
        "contact.placeholderPhone": "+964XXXXXXXXX",
        "contact.placeholderMessage": "أخبرنا كيف يمكننا مساعدتك...",
        "contact.sendMessage": "إرسال الرسالة",
        "contact.send": "إرسال",
        "contact.sending": "جاري الإرسال...",
        "contact.successMessage": "تم إرسال الرسالة بنجاح! سنتواصل معك قريباً.",

        // Footer
        "footer.quickLinks": "روابط سريعة",
        "footer.contactUs": "اتصل بنا",
        "footer.followUs": "تابعنا",
        "footer.rights": "© {year} التاج لتأجير السيارات. جميع الحقوق محفوظة.",
        "footer.privacy": "سياسة الخصوصية",
        "footer.terms": "شروط الخدمة",

        // Admin
        "admin.dashboard": "لوحة التحكم",
        "admin.cars": "السيارات",
        "admin.bookings": "الحجوزات",
        "admin.calendar": "التقويم",
        "admin.crm": "العملاء",
        "admin.categories": "الفئات",
        "admin.branches": "الفروع",
        "admin.exitAdmin": "خروج",
        "admin.viewSite": "عرض الموقع",
        "admin.welcome": "مرحباً بك في",
        "admin.welcomeHighlight": "إدارة التاج",
        "admin.manageFleet": "أدر أسطولك، حجوزاتك، وفئاتك من هنا.",
        "admin.totalCars": "إجمالي السيارات",
        "admin.availableCars": "متاحة",
        "admin.totalBookings": "إجمالي الحجوزات",
        "admin.pending": "قيد الانتظار",
        "admin.totalRevenue": "إجمالي الإيرادات",
        "admin.revenueNote": "من الحجوزات المؤكدة والمكتملة",
        "admin.recentBookings": "آخر الحجوزات",
        "admin.viewAll": "عرض الكل",
        "admin.noBookingsYet": "لا توجد حجوزات بعد. ستظهر هنا عندما يبدأ العملاء بالحجز.",
        "admin.addNewCar": "إضافة سيارة",
        "admin.manageBookings": "إدارة الحجوزات",
        "admin.addVehicle": "أضف سيارة لأسطولك",
        "admin.viewReservations": "عرض وتحديث الحجوزات",
        "admin.organizeTypes": "تنظيم أنواع السيارات",
        "admin.newBookings": "جديد",

        // Admin Bookings
        "admin.manageBookingsTitle": "إدارة الحجوزات",
        "admin.totalBookingsCount": "إجمالي الحجوزات",
        "admin.searchBookings": "البحث بالاسم، الهاتف، السيارة أو الفرع...",
        "admin.allStatus": "جميع الحالات",
        "admin.statusPending": "قيد الانتظار",
        "admin.statusConfirmed": "مؤكد",
        "admin.statusCompleted": "مكتمل",
        "admin.statusCancelled": "ملغي",
        "admin.noBookingsMatch": "لا توجد حجوزات مطابقة للبحث",
        "admin.bookingDetails": "تفاصيل الحجز",
        "admin.customerInfo": "معلومات العميل",
        "admin.carInfo": "السيارة",
        "admin.bookingDetailsTitle": "تفاصيل الحجز",
        "admin.pickupDate": "تاريخ الاستلام",
        "admin.returnDate": "تاريخ الإرجاع",
        "admin.pickupTime": "وقت الاستلام",
        "admin.branchLocation": "الفرع",
        "admin.totalAmount": "المبلغ الإجمالي",
        "admin.updateStatus": "تحديث الحالة",
        "admin.notes": "ملاحظات",

        // Admin Cars
        "admin.manageCars": "إدارة السيارات",
        "admin.searchCars": "البحث بالاسم أو الموديل...",
        "admin.noCarsYet": "لا توجد سيارات بعد. أضف أول سيارة!",
        "admin.noCarsMatch": "لا توجد سيارات مطابقة للبحث",
        "admin.addCar": "إضافة سيارة",
        "admin.editCar": "تعديل السيارة",
        "admin.carName": "اسم السيارة",
        "admin.carNameEn": "الاسم (بالإنجليزية)",
        "admin.carNameAr": "الاسم (بالعربية)",
        "admin.carModel": "الموديل",
        "admin.carYear": "السنة",
        "admin.carColor": "اللون",
        "admin.carDailyRate": "السعر اليومي",
        "admin.carCategory": "الفئة",
        "admin.carStatus": "الحالة",
        "admin.carFeatures": "المميزات",
        "admin.carImages": "الصور",
        "admin.uploadImages": "رفع الصور",
        "admin.selectCategory": "اختر الفئة",
        "admin.featuresPlaceholder": "مثال: مقاعد جلدية، فتحة سقف، GPS",
        "admin.confirmDelete": "هل أنت متأكد من الحذف؟",

        // Admin Categories
        "admin.manageCategories": "إدارة الفئات",
        "admin.noCategoriesYet": "لا توجد فئات بعد. أضف أول فئة!",
        "admin.addCategory": "إضافة فئة",
        "admin.editCategory": "تعديل الفئة",
        "admin.categoryName": "اسم الفئة",
        "admin.categoryNameEn": "الاسم (بالإنجليزية)",
        "admin.categoryNameAr": "الاسم (بالعربية)",
        "admin.categoryDescription": "الوصف",

        // Admin Branches
        "admin.manageBranches": "إدارة الفروع",
        "admin.branchesSubtitle": "إدارة مواقع الاستلام والتسليم",
        "admin.noBranchesYet": "لا توجد فروع بعد. أضف أول فرع!",
        "admin.addBranch": "إضافة فرع",
        "admin.editBranch": "تعديل الفرع",
        "admin.newBranch": "فرع جديد",
        "admin.branchName": "اسم الفرع",
        "admin.branchNameEn": "الاسم (بالإنجليزية)",
        "admin.branchNameAr": "الاسم (بالعربية)",
        "admin.branchAddress": "العنوان",
        "admin.branchAddressEn": "العنوان (بالإنجليزية)",
        "admin.branchAddressAr": "العنوان (بالعربية)",
        "admin.branchPhone": "الهاتف",
        "admin.branchActive": "نشط",

        // Common
        "common.loading": "جاري التحميل...",
        "common.error": "خطأ",
        "common.save": "حفظ",
        "common.cancel": "إلغاء",
        "common.edit": "تعديل",
        "common.delete": "حذف",
        "common.add": "إضافة",
        "common.update": "تحديث",
        "common.search": "بحث",
        "common.filter": "تصفية",
        "common.actions": "إجراءات",
        "common.status": "الحالة",
        "common.active": "نشط",
        "common.inactive": "غير نشط",
        "common.customer": "العميل",
        "common.car": "السيارة",
        "common.dates": "التواريخ",
        "common.amount": "المبلغ",
        "common.name": "الاسم",
        "common.phone": "الهاتف",
        "common.email": "البريد الإلكتروني",
        "common.address": "العنوان",
        "common.yes": "نعم",
        "common.no": "لا",
        "common.confirm": "تأكيد",
        "common.close": "إغلاق",
        "common.back": "رجوع",
        "common.next": "التالي",
        "common.required": "مطلوب",
        "common.chatWithUs": "تواصل معنا",
        "common.whatsappMessage": "مرحباً، أنا مهتم باستئجار سيارة من شركة التاج.",
        "common.optional": "اختياري",

        // User Management
        "admin.userManagement": "إدارة المستخدمين",
        "admin.users": "المستخدمين",
        "admin.addUser": "إضافة مستخدم",
        "admin.editUser": "تعديل مستخدم",
        "admin.role": "الصلاحية",
        "admin.roleSuperAdmin": "مدير عام",
        "admin.roleBranchManager": "مدير فرع",
        "admin.roleStaff": "موظف",
        "admin.assignedBranches": "الفروع المعينة",
        "admin.allBranches": "جميع الفروع",
        "admin.activeStatus": "حالة النشاط",
        "admin.fullName": "الاسم الكامل",
        "admin.email": "البريد الإلكتروني",
        "admin.password": "كلمة المرور",
        "admin.passwordNote": "اتركه فارغاً للحفاظ على كلمة المرور الحالية عند التعديل",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>("en");

    useEffect(() => {
        const saved = localStorage.getItem("language") as Language;
        if (saved && (saved === "en" || saved === "ar")) {
            setLanguageState(saved);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("language", lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    const dir = language === "ar" ? "rtl" : "ltr";

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
